"""add attendance sessions

Revision ID: 5e93c7c182db
Revises: 95a3fab5389b
Create Date: 2026-08-22 18:40:15.148358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e93c7c182db'
down_revision: Union[str, Sequence[str], None] = '95a3fab5389b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_class_id'), 'attendance_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_date'), 'attendance_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_expires_at'), 'attendance_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_id'), 'attendance_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_token'), 'attendance_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_attendance_sessions_status'), 'attendance_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_subject_id'), 'attendance_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_subject_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_status'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_token'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_expires_at'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_class_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
