"""add attendance correction audit trail

Revision ID: 9b9f018e5d2c
Revises: 74109eb580fc
Create Date: 2026-08-23 16:21:45.602293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9f018e5d2c'
down_revision: Union[str, Sequence[str], None] = '74109eb580fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('corrected_by', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_corrections_attendance_id'), 'attendance_corrections', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_corrected_by'), 'attendance_corrections', ['corrected_by'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_id'), 'attendance_corrections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_corrections_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_corrected_by'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_attendance_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    # ### end Alembic commands ###
