"""add departments classes students teachers

Revision ID: ba6c3e53822e
Revises: e2d843f8d291
Create Date: 2026-08-19 23:37:24.872197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6c3e53822e'
down_revision: Union[str, Sequence[str], None] = 'e2d843f8d291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=10), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_academic_year'), 'classes', ['academic_year'], unique=False)
    op.create_index(op.f('ix_classes_department_id'), 'classes', ['department_id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_department_id'), 'teachers', ['department_id'], unique=False)
    op.create_index(op.f('ix_teachers_employee_id'), 'teachers', ['employee_id'], unique=True)
    op.create_index(op.f('ix_teachers_is_active'), 'teachers', ['is_active'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_number', sa.String(length=50), nullable=False),
    sa.Column('roll_number', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=10), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_enrollment_number'), 'students', ['enrollment_number'], unique=True)
    op.create_index(op.f('ix_students_is_active'), 'students', ['is_active'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_is_active'), table_name='students')
    op.drop_index(op.f('ix_students_enrollment_number'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_is_active'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_employee_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_department_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_department_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academic_year'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
